In [2]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris


set target and feature variables

In [3]:
iris = load_iris()
X = iris.data
Y = iris.target

Normalize Data

In [4]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
sc.fit(X)
X = sc.transform(X)

Split Data

In [5]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,Y,test_size=0.2,random_state=0)

Training The Model

In [9]:
from sklearn.linear_model import LogisticRegression
# use l1 regulization technique for better results
lr = LogisticRegression()
lr.fit(X_train,y_train)


LogisticRegression()

Evaluate Model Perfomance

In [17]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
y_pred = lr.predict(X_test)
print("Train-Accuracy",accuracy_score(y_train,lr.predict(X_train)))
print("Train-Confusion-Matrix--")
print(confusion_matrix(y_train,lr.predict(X_train)))
# Testing Accuracy
print("Test-Accuracy",accuracy_score(y_test,y_pred))

Train-Accuracy 0.9583333333333334
Train-Confusion-Matrix--
[[39  0  0]
 [ 0 34  3]
 [ 0  2 42]]
Test-Accuracy 1.0
